### ISSUE TITLE
ErrorException Undefined index:

### ISSUE THREAD

**Issue by newbie2005** [freshbitsweb/laratables#22]
Server side 
use App\User;
use Freshbitsweb\Laratables\Laratables;

function getdata()
{
return Laratables::recordsOf(User::class); 
}

When run \getdata
Show 
(1/1) ErrorExceptionUndefined index:
--
in ColumnManager.php line 168
at HandleExceptions->handleError(8, 'Undefined index: ', '/home/html/xxxx/vendor/freshbitsweb/laratables/src/ColumnManager.php', 168,array('requestedColumnNames' => array(), 'order' => null))in ColumnManager.php line 168
at ColumnManager->getOrderColumn()in ColumnManager.php line 145

**Comment by gauravmak** [comment]
Seems like Datatables is not specifying the order to be ordered. Have you specifically coded anything related on client side? If not, which version of Datatables are you using?

**Comment by newbie2005** [comment]
run ip/path/getdata is server side, not relate to client side.
I  use Mysql 5.7 and have primary key - ID

**Comment by gauravmak** [comment]
The default ajax request that Datatables makes to fetch the data contains the parameter to order the records. The errors seem to be occurring because that parameter is missing from the request.

Can you show your client-side code, please?

**Comment by newbie2005** [comment]
After study code of demo of the package, I fixed the problem

**Comment by codefanatic** [comment]
@newbie2005 care to share some light on this?  What did you do to fix the issue

**Comment by kfulk14** [comment]
@newbie2005 same I am still having the same issue even after following the demo. How did you solve this?

**Comment by ajgentile** [comment]
Bump.

**Comment by bonucci** [comment]
SAme issue, any solution? Is giving exactly in te User class

**Comment by gauravmak** [comment]
Seems like a few more developers are facing the issue. Please share your client-side code, friends.

**Comment by ajgentile** [comment]
I went back to building the data directly. Will keep my eye out for updates to the package.

**Comment by gauravmak** [comment]
If anyone faces this issue again, please create a new one with client-side code, thanks.
